// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeg9B2a4didTUYEB88bGmPL_Ft5VrUhTI',
    appId: '1:904679322459:web:b7bc84c2c191309883607e',
    messagingSenderId: '904679322459',
    projectId: 'schulplaner-a4b76',
    authDomain: 'schulplaner-a4b76.firebaseapp.com',
    storageBucket: 'schulplaner-a4b76.appspot.com',
    measurementId: 'G-ST2XCPQ333',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqu9S5g0tuimpt6__1yzL3ZOo1B1lkBSs',
    appId: '1:904679322459:android:ba58bd3414ddbc3d83607e',
    messagingSenderId: '904679322459',
    projectId: 'schulplaner-a4b76',
    storageBucket: 'schulplaner-a4b76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfWyDW24qHueBuj4k8a1rBTscoxsGq8zI',
    appId: '1:904679322459:ios:e042879bc4da54a983607e',
    messagingSenderId: '904679322459',
    projectId: 'schulplaner-a4b76',
    storageBucket: 'schulplaner-a4b76.appspot.com',
    iosClientId: '904679322459-aqt2abht81t3q57i7l35jogkofns7i22.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfWyDW24qHueBuj4k8a1rBTscoxsGq8zI',
    appId: '1:904679322459:ios:e042879bc4da54a983607e',
    messagingSenderId: '904679322459',
    projectId: 'schulplaner-a4b76',
    storageBucket: 'schulplaner-a4b76.appspot.com',
    iosClientId: '904679322459-aqt2abht81t3q57i7l35jogkofns7i22.apps.googleusercontent.com',
    iosBundleId: 'com.example.gitpodFlutterQuickstart',
  );
}
